default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: database_example_development

test:
  <<: *default
  database: database_example_test

production:
  <<: *default
  database: database_example_production
